# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import LeapPython
else:
    import LeapPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = LeapPython.delete_SwigPyIterator

    def value(self):
        return LeapPython.SwigPyIterator_value(self)

    def incr(self, n=1):
        return LeapPython.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return LeapPython.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return LeapPython.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return LeapPython.SwigPyIterator_equal(self, x)

    def copy(self):
        return LeapPython.SwigPyIterator_copy(self)

    def next(self):
        return LeapPython.SwigPyIterator_next(self)

    def __next__(self):
        return LeapPython.SwigPyIterator___next__(self)

    def previous(self):
        return LeapPython.SwigPyIterator_previous(self)

    def advance(self, n):
        return LeapPython.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return LeapPython.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return LeapPython.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return LeapPython.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return LeapPython.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return LeapPython.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return LeapPython.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in LeapPython:
LeapPython.SwigPyIterator_swigregister(SwigPyIterator)

class byte_array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        LeapPython.byte_array_swiginit(self, LeapPython.new_byte_array(nelements))
    __swig_destroy__ = LeapPython.delete_byte_array

    def __getitem__(self, index):
        return LeapPython.byte_array___getitem__(self, index)

    def __setitem__(self, index, value):
        return LeapPython.byte_array___setitem__(self, index, value)

    def cast(self):
        return LeapPython.byte_array_cast(self)

    @staticmethod
    def frompointer(t):
        return LeapPython.byte_array_frompointer(t)

# Register byte_array in LeapPython:
LeapPython.byte_array_swigregister(byte_array)

def byte_array_frompointer(t):
    return LeapPython.byte_array_frompointer(t)

class float_array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        LeapPython.float_array_swiginit(self, LeapPython.new_float_array(nelements))
    __swig_destroy__ = LeapPython.delete_float_array

    def __getitem__(self, index):
        return LeapPython.float_array___getitem__(self, index)

    def __setitem__(self, index, value):
        return LeapPython.float_array___setitem__(self, index, value)

    def cast(self):
        return LeapPython.float_array_cast(self)

    @staticmethod
    def frompointer(t):
        return LeapPython.float_array_frompointer(t)

# Register float_array in LeapPython:
LeapPython.float_array_swigregister(float_array)

def float_array_frompointer(t):
    return LeapPython.float_array_frompointer(t)

class Vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        LeapPython.Vector_swiginit(self, LeapPython.new_Vector(*args))

    def distance_to(self, other):
        return LeapPython.Vector_distance_to(self, other)

    def angle_to(self, other):
        return LeapPython.Vector_angle_to(self, other)

    def dot(self, other):
        return LeapPython.Vector_dot(self, other)

    def cross(self, other):
        return LeapPython.Vector_cross(self, other)

    def __neg__(self):
        return LeapPython.Vector___neg__(self)

    def __add__(self, other):
        return LeapPython.Vector___add__(self, other)

    def __sub__(self, other):
        return LeapPython.Vector___sub__(self, other)

    def __mul__(self, scalar):
        return LeapPython.Vector___mul__(self, scalar)

    def __truediv__(self, *args):
        return LeapPython.Vector___truediv__(self, *args)
    __div__ = __truediv__



    def __iadd__(self, other):
        return LeapPython.Vector___iadd__(self, other)

    def __isub__(self, other):
        return LeapPython.Vector___isub__(self, other)

    def __imul__(self, scalar):
        return LeapPython.Vector___imul__(self, scalar)

    def __itruediv__(self, *args):
        return LeapPython.Vector___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __str__(self):
        return LeapPython.Vector___str__(self)

    def __eq__(self, other):
        return LeapPython.Vector___eq__(self, other)

    def __ne__(self, other):
        return LeapPython.Vector___ne__(self, other)

    def is_valid(self):
        return LeapPython.Vector_is_valid(self)

    def __getitem__(self, index):
        return LeapPython.Vector___getitem__(self, index)
    x = property(LeapPython.Vector_x_get, LeapPython.Vector_x_set)
    y = property(LeapPython.Vector_y_get, LeapPython.Vector_y_set)
    z = property(LeapPython.Vector_z_get, LeapPython.Vector_z_set)
    magnitude = property(LeapPython.Vector_magnitude_get)
    magnitude_squared = property(LeapPython.Vector_magnitude_squared_get)
    pitch = property(LeapPython.Vector_pitch_get)
    roll = property(LeapPython.Vector_roll_get)
    yaw = property(LeapPython.Vector_yaw_get)
    normalized = property(LeapPython.Vector_normalized_get)

    def to_float_array(self): return [self.x, self.y, self.z]
    def to_tuple(self): return (self.x, self.y, self.z)

    __swig_destroy__ = LeapPython.delete_Vector

# Register Vector in LeapPython:
LeapPython.Vector_swigregister(Vector)
cvar = LeapPython.cvar
PI = cvar.PI
DEG_TO_RAD = cvar.DEG_TO_RAD
RAD_TO_DEG = cvar.RAD_TO_DEG
EPSILON = cvar.EPSILON
Vector.zero = LeapPython.cvar.Vector_zero
Vector.x_axis = LeapPython.cvar.Vector_x_axis
Vector.y_axis = LeapPython.cvar.Vector_y_axis
Vector.z_axis = LeapPython.cvar.Vector_z_axis
Vector.forward = LeapPython.cvar.Vector_forward
Vector.backward = LeapPython.cvar.Vector_backward
Vector.left = LeapPython.cvar.Vector_left
Vector.right = LeapPython.cvar.Vector_right
Vector.up = LeapPython.cvar.Vector_up
Vector.down = LeapPython.cvar.Vector_down

class Matrix(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        LeapPython.Matrix_swiginit(self, LeapPython.new_Matrix(*args))

    def set_rotation(self, axis, angle_radians):
        return LeapPython.Matrix_set_rotation(self, axis, angle_radians)

    def transform_point(self, _in):
        return LeapPython.Matrix_transform_point(self, _in)

    def transform_direction(self, _in):
        return LeapPython.Matrix_transform_direction(self, _in)

    def rigid_inverse(self):
        return LeapPython.Matrix_rigid_inverse(self)

    def __mul__(self, other):
        return LeapPython.Matrix___mul__(self, other)

    def __imul__(self, other):
        return LeapPython.Matrix___imul__(self, other)

    def __eq__(self, other):
        return LeapPython.Matrix___eq__(self, other)

    def __ne__(self, other):
        return LeapPython.Matrix___ne__(self, other)

    def __str__(self):
        return LeapPython.Matrix___str__(self)
    x_basis = property(LeapPython.Matrix_x_basis_get, LeapPython.Matrix_x_basis_set)
    y_basis = property(LeapPython.Matrix_y_basis_get, LeapPython.Matrix_y_basis_set)
    z_basis = property(LeapPython.Matrix_z_basis_get, LeapPython.Matrix_z_basis_set)
    origin = property(LeapPython.Matrix_origin_get, LeapPython.Matrix_origin_set)

    def to_array_3x3(self, output = None):
        if output is None:
            output = [0]*9
        output[0], output[1], output[2] = self.x_basis.x, self.x_basis.y, self.x_basis.z
        output[3], output[4], output[5] = self.y_basis.x, self.y_basis.y, self.y_basis.z
        output[6], output[7], output[8] = self.z_basis.x, self.z_basis.y, self.z_basis.z
        return output
    def to_array_4x4(self, output = None):
        if output is None:
            output = [0]*16
        output[0],  output[1],  output[2],  output[3]  = self.x_basis.x, self.x_basis.y, self.x_basis.z, 0.0
        output[4],  output[5],  output[6],  output[7]  = self.y_basis.x, self.y_basis.y, self.y_basis.z, 0.0
        output[8],  output[9],  output[10], output[11] = self.z_basis.x, self.z_basis.y, self.z_basis.z, 0.0
        output[12], output[13], output[14], output[15] = self.origin.x,  self.origin.y,  self.origin.z,  1.0
        return output

    __swig_destroy__ = LeapPython.delete_Matrix

# Register Matrix in LeapPython:
LeapPython.Matrix_swigregister(Matrix)
Matrix.identity = LeapPython.cvar.Matrix_identity

class Interface(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

# Register Interface in LeapPython:
LeapPython.Interface_swigregister(Interface)

class Pointable(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ZONE_NONE = LeapPython.Pointable_ZONE_NONE
    ZONE_HOVERING = LeapPython.Pointable_ZONE_HOVERING
    ZONE_TOUCHING = LeapPython.Pointable_ZONE_TOUCHING

    def __init__(self):
        LeapPython.Pointable_swiginit(self, LeapPython.new_Pointable())

    def __eq__(self, arg2):
        return LeapPython.Pointable___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Pointable___ne__(self, arg2)

    def __str__(self):
        return LeapPython.Pointable___str__(self)
    id = property(LeapPython.Pointable_id_get)
    hand = property(LeapPython.Pointable_hand_get)
    tip_position = property(LeapPython.Pointable_tip_position_get)
    tip_velocity = property(LeapPython.Pointable_tip_velocity_get)
    direction = property(LeapPython.Pointable_direction_get)
    width = property(LeapPython.Pointable_width_get)
    length = property(LeapPython.Pointable_length_get)
    is_tool = property(LeapPython.Pointable_is_tool_get)
    is_finger = property(LeapPython.Pointable_is_finger_get)
    is_extended = property(LeapPython.Pointable_is_extended_get)
    is_valid = property(LeapPython.Pointable_is_valid_get)
    touch_zone = property(LeapPython.Pointable_touch_zone_get)
    touch_distance = property(LeapPython.Pointable_touch_distance_get)
    stabilized_tip_position = property(LeapPython.Pointable_stabilized_tip_position_get)
    time_visible = property(LeapPython.Pointable_time_visible_get)
    frame = property(LeapPython.Pointable_frame_get)
    __swig_destroy__ = LeapPython.delete_Pointable

# Register Pointable in LeapPython:
LeapPython.Pointable_swigregister(Pointable)
Pointable.invalid = LeapPython.cvar.Pointable_invalid

class Arm(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.Arm_swiginit(self, LeapPython.new_Arm())

    def __eq__(self, arg2):
        return LeapPython.Arm___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Arm___ne__(self, arg2)

    def __str__(self):
        return LeapPython.Arm___str__(self)
    width = property(LeapPython.Arm_width_get)
    center = property(LeapPython.Arm_center_get)
    direction = property(LeapPython.Arm_direction_get)
    basis = property(LeapPython.Arm_basis_get)
    elbow_position = property(LeapPython.Arm_elbow_position_get)
    wrist_position = property(LeapPython.Arm_wrist_position_get)
    is_valid = property(LeapPython.Arm_is_valid_get)
    __swig_destroy__ = LeapPython.delete_Arm

# Register Arm in LeapPython:
LeapPython.Arm_swigregister(Arm)
Arm.invalid = LeapPython.cvar.Arm_invalid

class Bone(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    TYPE_METACARPAL = LeapPython.Bone_TYPE_METACARPAL
    TYPE_PROXIMAL = LeapPython.Bone_TYPE_PROXIMAL
    TYPE_INTERMEDIATE = LeapPython.Bone_TYPE_INTERMEDIATE
    TYPE_DISTAL = LeapPython.Bone_TYPE_DISTAL

    def __init__(self):
        LeapPython.Bone_swiginit(self, LeapPython.new_Bone())

    def __eq__(self, arg2):
        return LeapPython.Bone___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Bone___ne__(self, arg2)

    def __str__(self):
        return LeapPython.Bone___str__(self)
    prev_joint = property(LeapPython.Bone_prev_joint_get)
    next_joint = property(LeapPython.Bone_next_joint_get)
    center = property(LeapPython.Bone_center_get)
    direction = property(LeapPython.Bone_direction_get)
    length = property(LeapPython.Bone_length_get)
    width = property(LeapPython.Bone_width_get)
    type = property(LeapPython.Bone_type_get)
    basis = property(LeapPython.Bone_basis_get)
    is_valid = property(LeapPython.Bone_is_valid_get)
    __swig_destroy__ = LeapPython.delete_Bone

# Register Bone in LeapPython:
LeapPython.Bone_swigregister(Bone)
Bone.invalid = LeapPython.cvar.Bone_invalid

class Finger(Pointable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    JOINT_MCP = LeapPython.Finger_JOINT_MCP
    JOINT_PIP = LeapPython.Finger_JOINT_PIP
    JOINT_DIP = LeapPython.Finger_JOINT_DIP
    JOINT_TIP = LeapPython.Finger_JOINT_TIP
    TYPE_THUMB = LeapPython.Finger_TYPE_THUMB
    TYPE_INDEX = LeapPython.Finger_TYPE_INDEX
    TYPE_MIDDLE = LeapPython.Finger_TYPE_MIDDLE
    TYPE_RING = LeapPython.Finger_TYPE_RING
    TYPE_PINKY = LeapPython.Finger_TYPE_PINKY

    def __init__(self, *args):
        LeapPython.Finger_swiginit(self, LeapPython.new_Finger(*args))

    def joint_position(self, joint_ix):
        return LeapPython.Finger_joint_position(self, joint_ix)

    def bone(self, bone_ix):
        return LeapPython.Finger_bone(self, bone_ix)

    def __str__(self):
        return LeapPython.Finger___str__(self)
    type = property(LeapPython.Finger_type_get)
    __swig_destroy__ = LeapPython.delete_Finger

# Register Finger in LeapPython:
LeapPython.Finger_swigregister(Finger)
Finger.invalid = LeapPython.cvar.Finger_invalid

class Tool(Pointable):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        LeapPython.Tool_swiginit(self, LeapPython.new_Tool(*args))

    def __str__(self):
        return LeapPython.Tool___str__(self)
    __swig_destroy__ = LeapPython.delete_Tool

# Register Tool in LeapPython:
LeapPython.Tool_swigregister(Tool)
Tool.invalid = LeapPython.cvar.Tool_invalid

class Hand(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.Hand_swiginit(self, LeapPython.new_Hand())

    def pointable(self, id):
        return LeapPython.Hand_pointable(self, id)

    def finger(self, id):
        return LeapPython.Hand_finger(self, id)

    def translation(self, since_frame):
        return LeapPython.Hand_translation(self, since_frame)

    def translation_probability(self, since_frame):
        return LeapPython.Hand_translation_probability(self, since_frame)

    def rotation_axis(self, since_frame):
        return LeapPython.Hand_rotation_axis(self, since_frame)

    def rotation_angle(self, *args):
        return LeapPython.Hand_rotation_angle(self, *args)

    def rotation_matrix(self, since_frame):
        return LeapPython.Hand_rotation_matrix(self, since_frame)

    def rotation_probability(self, since_frame):
        return LeapPython.Hand_rotation_probability(self, since_frame)

    def scale_factor(self, since_frame):
        return LeapPython.Hand_scale_factor(self, since_frame)

    def scale_probability(self, since_frame):
        return LeapPython.Hand_scale_probability(self, since_frame)

    def __eq__(self, arg2):
        return LeapPython.Hand___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Hand___ne__(self, arg2)

    def __str__(self):
        return LeapPython.Hand___str__(self)
    id = property(LeapPython.Hand_id_get)
    pointables = property(LeapPython.Hand_pointables_get)
    fingers = property(LeapPython.Hand_fingers_get)
    palm_position = property(LeapPython.Hand_palm_position_get)
    palm_velocity = property(LeapPython.Hand_palm_velocity_get)
    palm_normal = property(LeapPython.Hand_palm_normal_get)
    direction = property(LeapPython.Hand_direction_get)
    basis = property(LeapPython.Hand_basis_get)
    is_valid = property(LeapPython.Hand_is_valid_get)
    sphere_center = property(LeapPython.Hand_sphere_center_get)
    sphere_radius = property(LeapPython.Hand_sphere_radius_get)
    grab_angle = property(LeapPython.Hand_grab_angle_get)
    pinch_distance = property(LeapPython.Hand_pinch_distance_get)
    grab_strength = property(LeapPython.Hand_grab_strength_get)
    pinch_strength = property(LeapPython.Hand_pinch_strength_get)
    palm_width = property(LeapPython.Hand_palm_width_get)
    stabilized_palm_position = property(LeapPython.Hand_stabilized_palm_position_get)
    wrist_position = property(LeapPython.Hand_wrist_position_get)
    time_visible = property(LeapPython.Hand_time_visible_get)
    confidence = property(LeapPython.Hand_confidence_get)
    is_left = property(LeapPython.Hand_is_left_get)
    is_right = property(LeapPython.Hand_is_right_get)
    frame = property(LeapPython.Hand_frame_get)
    arm = property(LeapPython.Hand_arm_get)
    __swig_destroy__ = LeapPython.delete_Hand

# Register Hand in LeapPython:
LeapPython.Hand_swigregister(Hand)
Hand.invalid = LeapPython.cvar.Hand_invalid

class Gesture(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    TYPE_INVALID = LeapPython.Gesture_TYPE_INVALID
    TYPE_SWIPE = LeapPython.Gesture_TYPE_SWIPE
    TYPE_CIRCLE = LeapPython.Gesture_TYPE_CIRCLE
    TYPE_SCREEN_TAP = LeapPython.Gesture_TYPE_SCREEN_TAP
    TYPE_KEY_TAP = LeapPython.Gesture_TYPE_KEY_TAP
    STATE_INVALID = LeapPython.Gesture_STATE_INVALID
    STATE_START = LeapPython.Gesture_STATE_START
    STATE_UPDATE = LeapPython.Gesture_STATE_UPDATE
    STATE_STOP = LeapPython.Gesture_STATE_STOP

    def __init__(self, *args):
        LeapPython.Gesture_swiginit(self, LeapPython.new_Gesture(*args))

    def __eq__(self, rhs):
        return LeapPython.Gesture___eq__(self, rhs)

    def __ne__(self, rhs):
        return LeapPython.Gesture___ne__(self, rhs)

    def __str__(self):
        return LeapPython.Gesture___str__(self)
    type = property(LeapPython.Gesture_type_get)
    state = property(LeapPython.Gesture_state_get)
    id = property(LeapPython.Gesture_id_get)
    duration = property(LeapPython.Gesture_duration_get)
    duration_seconds = property(LeapPython.Gesture_duration_seconds_get)
    frame = property(LeapPython.Gesture_frame_get)
    hands = property(LeapPython.Gesture_hands_get)
    pointables = property(LeapPython.Gesture_pointables_get)
    is_valid = property(LeapPython.Gesture_is_valid_get)
    __swig_destroy__ = LeapPython.delete_Gesture

# Register Gesture in LeapPython:
LeapPython.Gesture_swigregister(Gesture)
Gesture.invalid = LeapPython.cvar.Gesture_invalid

class SwipeGesture(Gesture):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def class_type():
        return LeapPython.SwipeGesture_class_type()

    def __init__(self, *args):
        LeapPython.SwipeGesture_swiginit(self, LeapPython.new_SwipeGesture(*args))
    start_position = property(LeapPython.SwipeGesture_start_position_get)
    position = property(LeapPython.SwipeGesture_position_get)
    direction = property(LeapPython.SwipeGesture_direction_get)
    speed = property(LeapPython.SwipeGesture_speed_get)
    pointable = property(LeapPython.SwipeGesture_pointable_get)
    __swig_destroy__ = LeapPython.delete_SwipeGesture

# Register SwipeGesture in LeapPython:
LeapPython.SwipeGesture_swigregister(SwipeGesture)

def SwipeGesture_class_type():
    return LeapPython.SwipeGesture_class_type()

class CircleGesture(Gesture):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def class_type():
        return LeapPython.CircleGesture_class_type()

    def __init__(self, *args):
        LeapPython.CircleGesture_swiginit(self, LeapPython.new_CircleGesture(*args))
    center = property(LeapPython.CircleGesture_center_get)
    normal = property(LeapPython.CircleGesture_normal_get)
    progress = property(LeapPython.CircleGesture_progress_get)
    radius = property(LeapPython.CircleGesture_radius_get)
    pointable = property(LeapPython.CircleGesture_pointable_get)
    __swig_destroy__ = LeapPython.delete_CircleGesture

# Register CircleGesture in LeapPython:
LeapPython.CircleGesture_swigregister(CircleGesture)

def CircleGesture_class_type():
    return LeapPython.CircleGesture_class_type()

class ScreenTapGesture(Gesture):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def class_type():
        return LeapPython.ScreenTapGesture_class_type()

    def __init__(self, *args):
        LeapPython.ScreenTapGesture_swiginit(self, LeapPython.new_ScreenTapGesture(*args))
    position = property(LeapPython.ScreenTapGesture_position_get)
    direction = property(LeapPython.ScreenTapGesture_direction_get)
    progress = property(LeapPython.ScreenTapGesture_progress_get)
    pointable = property(LeapPython.ScreenTapGesture_pointable_get)
    __swig_destroy__ = LeapPython.delete_ScreenTapGesture

# Register ScreenTapGesture in LeapPython:
LeapPython.ScreenTapGesture_swigregister(ScreenTapGesture)

def ScreenTapGesture_class_type():
    return LeapPython.ScreenTapGesture_class_type()

class KeyTapGesture(Gesture):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def class_type():
        return LeapPython.KeyTapGesture_class_type()

    def __init__(self, *args):
        LeapPython.KeyTapGesture_swiginit(self, LeapPython.new_KeyTapGesture(*args))
    position = property(LeapPython.KeyTapGesture_position_get)
    direction = property(LeapPython.KeyTapGesture_direction_get)
    progress = property(LeapPython.KeyTapGesture_progress_get)
    pointable = property(LeapPython.KeyTapGesture_pointable_get)
    __swig_destroy__ = LeapPython.delete_KeyTapGesture

# Register KeyTapGesture in LeapPython:
LeapPython.KeyTapGesture_swigregister(KeyTapGesture)

def KeyTapGesture_class_type():
    return LeapPython.KeyTapGesture_class_type()

class Device(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    TYPE_PERIPHERAL = LeapPython.Device_TYPE_PERIPHERAL
    TYPE_HP_LEGACY = LeapPython.Device_TYPE_HP_LEGACY
    TYPE_KEYBOARD = LeapPython.Device_TYPE_KEYBOARD
    TYPE_LAPTOP = LeapPython.Device_TYPE_LAPTOP

    def __init__(self):
        LeapPython.Device_swiginit(self, LeapPython.new_Device())

    def distance_to_boundary(self, position):
        return LeapPython.Device_distance_to_boundary(self, position)

    def __eq__(self, arg2):
        return LeapPython.Device___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Device___ne__(self, arg2)

    def __str__(self):
        return LeapPython.Device___str__(self)
    horizontal_view_angle = property(LeapPython.Device_horizontal_view_angle_get)
    vertical_view_angle = property(LeapPython.Device_vertical_view_angle_get)
    range = property(LeapPython.Device_range_get)
    baseline = property(LeapPython.Device_baseline_get)
    is_valid = property(LeapPython.Device_is_valid_get)
    is_embedded = property(LeapPython.Device_is_embedded_get)
    is_streaming = property(LeapPython.Device_is_streaming_get)
    is_smudged = property(LeapPython.Device_is_smudged_get)
    is_lighting_bad = property(LeapPython.Device_is_lighting_bad_get)
    type = property(LeapPython.Device_type_get)
    serial_number = property(LeapPython.Device_serial_number_get)
    position = property(LeapPython.Device_position_get)
    orientation = property(LeapPython.Device_orientation_get)
    __swig_destroy__ = LeapPython.delete_Device

# Register Device in LeapPython:
LeapPython.Device_swigregister(Device)
Device.invalid = LeapPython.cvar.Device_invalid

class FailedDevice(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    FAIL_UNKNOWN = LeapPython.FailedDevice_FAIL_UNKNOWN
    FAIL_CALIBRATION = LeapPython.FailedDevice_FAIL_CALIBRATION
    FAIL_FIRMWARE = LeapPython.FailedDevice_FAIL_FIRMWARE
    FAIL_TRANSPORT = LeapPython.FailedDevice_FAIL_TRANSPORT
    FAIL_CONTROL = LeapPython.FailedDevice_FAIL_CONTROL
    FAIL_COUNT = LeapPython.FailedDevice_FAIL_COUNT

    def __init__(self):
        LeapPython.FailedDevice_swiginit(self, LeapPython.new_FailedDevice())

    def is_valid(self):
        return LeapPython.FailedDevice_is_valid(self)

    @staticmethod
    def invalid():
        return LeapPython.FailedDevice_invalid()

    def __eq__(self, arg2):
        return LeapPython.FailedDevice___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.FailedDevice___ne__(self, arg2)
    pnp_id = property(LeapPython.FailedDevice_pnp_id_get)
    failure = property(LeapPython.FailedDevice_failure_get)
    __swig_destroy__ = LeapPython.delete_FailedDevice

# Register FailedDevice in LeapPython:
LeapPython.FailedDevice_swigregister(FailedDevice)

def FailedDevice_invalid():
    return LeapPython.FailedDevice_invalid()

class Image(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.Image_swiginit(self, LeapPython.new_Image())

    def data(self, dst):
        return LeapPython.Image_data(self, dst)

    def distortion(self, dst):
        return LeapPython.Image_distortion(self, dst)
    INFRARED = LeapPython.Image_INFRARED
    IBRG = LeapPython.Image_IBRG

    def rectify(self, uv):
        return LeapPython.Image_rectify(self, uv)

    def warp(self, xy):
        return LeapPython.Image_warp(self, xy)

    def __eq__(self, arg2):
        return LeapPython.Image___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Image___ne__(self, arg2)

    def __str__(self):
        return LeapPython.Image___str__(self)
    sequence_id = property(LeapPython.Image_sequence_id_get)
    id = property(LeapPython.Image_id_get)
    width = property(LeapPython.Image_width_get)
    height = property(LeapPython.Image_height_get)
    bytes_per_pixel = property(LeapPython.Image_bytes_per_pixel_get)
    format = property(LeapPython.Image_format_get)
    distortion_width = property(LeapPython.Image_distortion_width_get)
    distortion_height = property(LeapPython.Image_distortion_height_get)
    ray_offset_x = property(LeapPython.Image_ray_offset_x_get)
    ray_offset_y = property(LeapPython.Image_ray_offset_y_get)
    ray_scale_x = property(LeapPython.Image_ray_scale_x_get)
    ray_scale_y = property(LeapPython.Image_ray_scale_y_get)
    timestamp = property(LeapPython.Image_timestamp_get)
    is_valid = property(LeapPython.Image_is_valid_get)

    def data(self):
        ptr = byte_array(self.width * self.height * self.bytes_per_pixel)
        LeapPython.Image_data(self, ptr)
        return ptr
    def distortion(self):
        ptr = float_array(self.distortion_width * self.distortion_height)
        LeapPython.Image_distortion(self, ptr)
        return ptr
    #__swig_getmethods__["data"] = data
    #if _newclass:data = _swig_property(data)
    #__swig_getmethods__["distortion"] = distortion
    #if _newclass:distortion = _swig_property(distortion)

    data_pointer = property(LeapPython.Image_data_pointer_get)
    distortion_pointer = property(LeapPython.Image_distortion_pointer_get)
    __swig_destroy__ = LeapPython.delete_Image

# Register Image in LeapPython:
LeapPython.Image_swigregister(Image)
Image.invalid = LeapPython.cvar.Image_invalid

class PointableList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.PointableList_swiginit(self, LeapPython.new_PointableList())

    def __len__(self):
        return LeapPython.PointableList___len__(self)

    def __getitem__(self, index):
        return LeapPython.PointableList___getitem__(self, index)

    def append(self, *args):
        return LeapPython.PointableList_append(self, *args)

    def extended(self):
        return LeapPython.PointableList_extended(self)
    is_empty = property(LeapPython.PointableList_is_empty_get)
    leftmost = property(LeapPython.PointableList_leftmost_get)
    rightmost = property(LeapPython.PointableList_rightmost_get)
    frontmost = property(LeapPython.PointableList_frontmost_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_PointableList

# Register PointableList in LeapPython:
LeapPython.PointableList_swigregister(PointableList)

class FingerList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.FingerList_swiginit(self, LeapPython.new_FingerList())

    def __len__(self):
        return LeapPython.FingerList___len__(self)

    def __getitem__(self, index):
        return LeapPython.FingerList___getitem__(self, index)

    def append(self, other):
        return LeapPython.FingerList_append(self, other)

    def extended(self):
        return LeapPython.FingerList_extended(self)

    def finger_type(self, type):
        return LeapPython.FingerList_finger_type(self, type)
    is_empty = property(LeapPython.FingerList_is_empty_get)
    leftmost = property(LeapPython.FingerList_leftmost_get)
    rightmost = property(LeapPython.FingerList_rightmost_get)
    frontmost = property(LeapPython.FingerList_frontmost_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_FingerList

# Register FingerList in LeapPython:
LeapPython.FingerList_swigregister(FingerList)

class ToolList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.ToolList_swiginit(self, LeapPython.new_ToolList())

    def __len__(self):
        return LeapPython.ToolList___len__(self)

    def __getitem__(self, index):
        return LeapPython.ToolList___getitem__(self, index)

    def append(self, other):
        return LeapPython.ToolList_append(self, other)
    is_empty = property(LeapPython.ToolList_is_empty_get)
    leftmost = property(LeapPython.ToolList_leftmost_get)
    rightmost = property(LeapPython.ToolList_rightmost_get)
    frontmost = property(LeapPython.ToolList_frontmost_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_ToolList

# Register ToolList in LeapPython:
LeapPython.ToolList_swigregister(ToolList)

class HandList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.HandList_swiginit(self, LeapPython.new_HandList())

    def __len__(self):
        return LeapPython.HandList___len__(self)

    def __getitem__(self, index):
        return LeapPython.HandList___getitem__(self, index)

    def append(self, other):
        return LeapPython.HandList_append(self, other)
    is_empty = property(LeapPython.HandList_is_empty_get)
    leftmost = property(LeapPython.HandList_leftmost_get)
    rightmost = property(LeapPython.HandList_rightmost_get)
    frontmost = property(LeapPython.HandList_frontmost_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_HandList

# Register HandList in LeapPython:
LeapPython.HandList_swigregister(HandList)

class GestureList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.GestureList_swiginit(self, LeapPython.new_GestureList())

    def __len__(self):
        return LeapPython.GestureList___len__(self)

    def __getitem__(self, index):
        return LeapPython.GestureList___getitem__(self, index)

    def append(self, other):
        return LeapPython.GestureList_append(self, other)
    is_empty = property(LeapPython.GestureList_is_empty_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_GestureList

# Register GestureList in LeapPython:
LeapPython.GestureList_swigregister(GestureList)

class DeviceList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.DeviceList_swiginit(self, LeapPython.new_DeviceList())

    def __len__(self):
        return LeapPython.DeviceList___len__(self)

    def __getitem__(self, index):
        return LeapPython.DeviceList___getitem__(self, index)

    def append(self, other):
        return LeapPython.DeviceList_append(self, other)
    is_empty = property(LeapPython.DeviceList_is_empty_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_DeviceList

# Register DeviceList in LeapPython:
LeapPython.DeviceList_swigregister(DeviceList)

class FailedDeviceList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.FailedDeviceList_swiginit(self, LeapPython.new_FailedDeviceList())

    def __len__(self):
        return LeapPython.FailedDeviceList___len__(self)

    def __getitem__(self, index):
        return LeapPython.FailedDeviceList___getitem__(self, index)

    def append(self, other):
        return LeapPython.FailedDeviceList_append(self, other)
    is_empty = property(LeapPython.FailedDeviceList_is_empty_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_FailedDeviceList

# Register FailedDeviceList in LeapPython:
LeapPython.FailedDeviceList_swigregister(FailedDeviceList)

class ImageList(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.ImageList_swiginit(self, LeapPython.new_ImageList())

    def __len__(self):
        return LeapPython.ImageList___len__(self)

    def __getitem__(self, index):
        return LeapPython.ImageList___getitem__(self, index)

    def append(self, other):
        return LeapPython.ImageList_append(self, other)
    is_empty = property(LeapPython.ImageList_is_empty_get)

    def __iter__(self):
      _pos = 0
      while _pos < len(self):
        yield self[_pos]
        _pos += 1

    __swig_destroy__ = LeapPython.delete_ImageList

# Register ImageList in LeapPython:
LeapPython.ImageList_swigregister(ImageList)

class InteractionBox(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.InteractionBox_swiginit(self, LeapPython.new_InteractionBox())

    def normalize_point(self, position, clamp=True):
        return LeapPython.InteractionBox_normalize_point(self, position, clamp)

    def denormalize_point(self, normalized_position):
        return LeapPython.InteractionBox_denormalize_point(self, normalized_position)

    def __eq__(self, arg2):
        return LeapPython.InteractionBox___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.InteractionBox___ne__(self, arg2)

    def __str__(self):
        return LeapPython.InteractionBox___str__(self)
    center = property(LeapPython.InteractionBox_center_get)
    width = property(LeapPython.InteractionBox_width_get)
    height = property(LeapPython.InteractionBox_height_get)
    depth = property(LeapPython.InteractionBox_depth_get)
    is_valid = property(LeapPython.InteractionBox_is_valid_get)
    __swig_destroy__ = LeapPython.delete_InteractionBox

# Register InteractionBox in LeapPython:
LeapPython.InteractionBox_swigregister(InteractionBox)
InteractionBox.invalid = LeapPython.cvar.InteractionBox_invalid

class Frame(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.Frame_swiginit(self, LeapPython.new_Frame())

    def hand(self, id):
        return LeapPython.Frame_hand(self, id)

    def pointable(self, id):
        return LeapPython.Frame_pointable(self, id)

    def finger(self, id):
        return LeapPython.Frame_finger(self, id)

    def tool(self, id):
        return LeapPython.Frame_tool(self, id)

    def gesture(self, id):
        return LeapPython.Frame_gesture(self, id)

    def gestures(self, *args):
        return LeapPython.Frame_gestures(self, *args)

    def translation(self, since_frame):
        return LeapPython.Frame_translation(self, since_frame)

    def translation_probability(self, since_frame):
        return LeapPython.Frame_translation_probability(self, since_frame)

    def rotation_axis(self, since_frame):
        return LeapPython.Frame_rotation_axis(self, since_frame)

    def rotation_angle(self, *args):
        return LeapPython.Frame_rotation_angle(self, *args)

    def rotation_matrix(self, since_frame):
        return LeapPython.Frame_rotation_matrix(self, since_frame)

    def rotation_probability(self, since_frame):
        return LeapPython.Frame_rotation_probability(self, since_frame)

    def scale_factor(self, since_frame):
        return LeapPython.Frame_scale_factor(self, since_frame)

    def scale_probability(self, since_frame):
        return LeapPython.Frame_scale_probability(self, since_frame)

    def __eq__(self, arg2):
        return LeapPython.Frame___eq__(self, arg2)

    def __ne__(self, arg2):
        return LeapPython.Frame___ne__(self, arg2)

    def serialize(self, ptr):
        return LeapPython.Frame_serialize(self, ptr)

    def deserialize(self, ptr, length):
        return LeapPython.Frame_deserialize(self, ptr, length)

    def __str__(self):
        return LeapPython.Frame___str__(self)
    id = property(LeapPython.Frame_id_get)
    timestamp = property(LeapPython.Frame_timestamp_get)
    current_frames_per_second = property(LeapPython.Frame_current_frames_per_second_get)
    pointables = property(LeapPython.Frame_pointables_get)
    fingers = property(LeapPython.Frame_fingers_get)
    tools = property(LeapPython.Frame_tools_get)
    hands = property(LeapPython.Frame_hands_get)
    images = property(LeapPython.Frame_images_get)
    raw_images = property(LeapPython.Frame_raw_images_get)
    is_valid = property(LeapPython.Frame_is_valid_get)
    interaction_box = property(LeapPython.Frame_interaction_box_get)
    serialize_length = property(LeapPython.Frame_serialize_length_get)

    def serialize(self):
        length = self.serialize_length
        str = byte_array(length)
        LeapPython.Frame_serialize(self, str)
        return (str, length)
    def deserialize(self, tup):
        LeapPython.Frame_deserialize(self, tup[0], tup[1])
    #__swig_getmethods__["serialize"] = serialize
    #if _newclass:serialize = _swig_property(serialize)

    __swig_destroy__ = LeapPython.delete_Frame

# Register Frame in LeapPython:
LeapPython.Frame_swigregister(Frame)
Frame.invalid = LeapPython.cvar.Frame_invalid

class BugReport(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.BugReport_swiginit(self, LeapPython.new_BugReport())

    def begin_recording(self):
        return LeapPython.BugReport_begin_recording(self)

    def end_recording(self):
        return LeapPython.BugReport_end_recording(self)
    is_active = property(LeapPython.BugReport_is_active_get)
    progress = property(LeapPython.BugReport_progress_get)
    duration = property(LeapPython.BugReport_duration_get)
    __swig_destroy__ = LeapPython.delete_BugReport

# Register BugReport in LeapPython:
LeapPython.BugReport_swigregister(BugReport)

class Config(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        LeapPython.Config_swiginit(self, LeapPython.new_Config())
    TYPE_UNKNOWN = LeapPython.Config_TYPE_UNKNOWN
    TYPE_BOOLEAN = LeapPython.Config_TYPE_BOOLEAN
    TYPE_INT32 = LeapPython.Config_TYPE_INT32
    TYPE_FLOAT = LeapPython.Config_TYPE_FLOAT
    TYPE_STRING = LeapPython.Config_TYPE_STRING



















    def save(self):
        return LeapPython.Config_save(self)

    def get(self, *args):
      type = LeapPython.Config_type(self, *args)
      if type == LeapPython.Config_TYPE_BOOLEAN:
        return LeapPython.Config_get_bool(self, *args)
      elif type == LeapPython.Config_TYPE_INT32:
        return LeapPython.Config_get_int_32(self, *args)
      elif type == LeapPython.Config_TYPE_FLOAT:
        return LeapPython.Config_get_float(self, *args)
      elif type == LeapPython.Config_TYPE_STRING:
        return LeapPython.Config_get_string(self, *args)
      return None
    def set(self, *args):
      type = LeapPython.Config_type(self, *args[:-1])  # Do not pass value through
      if type == LeapPython.Config_TYPE_BOOLEAN:
        return LeapPython.Config_set_bool(self, *args)
      elif type == LeapPython.Config_TYPE_INT32:
        return LeapPython.Config_set_int_32(self, *args)
      elif type == LeapPython.Config_TYPE_FLOAT:
        return LeapPython.Config_set_float(self, *args)
      elif type == LeapPython.Config_TYPE_STRING:
        return LeapPython.Config_set_string(self, *args)
      return False

    __swig_destroy__ = LeapPython.delete_Config

# Register Config in LeapPython:
LeapPython.Config_swigregister(Config)

class Controller(Interface):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = LeapPython.delete_Controller

    def __init__(self, *args):
        LeapPython.Controller_swiginit(self, LeapPython.new_Controller(*args))

    def is_service_connected(self):
        return LeapPython.Controller_is_service_connected(self)
    POLICY_DEFAULT = LeapPython.Controller_POLICY_DEFAULT
    POLICY_BACKGROUND_FRAMES = LeapPython.Controller_POLICY_BACKGROUND_FRAMES
    POLICY_IMAGES = LeapPython.Controller_POLICY_IMAGES
    POLICY_OPTIMIZE_HMD = LeapPython.Controller_POLICY_OPTIMIZE_HMD
    POLICY_ALLOW_PAUSE_RESUME = LeapPython.Controller_POLICY_ALLOW_PAUSE_RESUME
    POLICY_RAW_IMAGES = LeapPython.Controller_POLICY_RAW_IMAGES

    def set_policy_flags(self, flags):
        return LeapPython.Controller_set_policy_flags(self, flags)

    def set_policy(self, policy):
        return LeapPython.Controller_set_policy(self, policy)

    def clear_policy(self, policy):
        return LeapPython.Controller_clear_policy(self, policy)

    def is_policy_set(self, policy):
        return LeapPython.Controller_is_policy_set(self, policy)

    def add_listener(self, listener):
        return LeapPython.Controller_add_listener(self, listener)

    def remove_listener(self, listener):
        return LeapPython.Controller_remove_listener(self, listener)

    def frame(self, history=0):
        return LeapPython.Controller_frame(self, history)

    def failed_devices(self):
        return LeapPython.Controller_failed_devices(self)

    def enable_gesture(self, type, enable=True):
        return LeapPython.Controller_enable_gesture(self, type, enable)

    def is_gesture_enabled(self, type):
        return LeapPython.Controller_is_gesture_enabled(self, type)

    def set_paused(self, pause):
        return LeapPython.Controller_set_paused(self, pause)

    def is_paused(self):
        return LeapPython.Controller_is_paused(self)

    def now(self):
        return LeapPython.Controller_now(self)
    is_connected = property(LeapPython.Controller_is_connected_get)
    has_focus = property(LeapPython.Controller_has_focus_get)
    policy_flags = property(LeapPython.Controller_policy_flags_get)
    config = property(LeapPython.Controller_config_get)
    images = property(LeapPython.Controller_images_get)
    raw_images = property(LeapPython.Controller_raw_images_get)
    devices = property(LeapPython.Controller_devices_get)
    bug_report = property(LeapPython.Controller_bug_report_get)

# Register Controller in LeapPython:
LeapPython.Controller_swigregister(Controller)

MESSAGE_UNKNOWN = LeapPython.MESSAGE_UNKNOWN
MESSAGE_CRITICAL = LeapPython.MESSAGE_CRITICAL
MESSAGE_WARNING = LeapPython.MESSAGE_WARNING
MESSAGE_INFORMATION = LeapPython.MESSAGE_INFORMATION
class Listener(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        if self.__class__ == Listener:
            _self = None
        else:
            _self = self
        LeapPython.Listener_swiginit(self, LeapPython.new_Listener(_self, ))
    __swig_destroy__ = LeapPython.delete_Listener

    def on_init(self, arg0):
        return LeapPython.Listener_on_init(self, arg0)

    def on_connect(self, arg0):
        return LeapPython.Listener_on_connect(self, arg0)

    def on_disconnect(self, arg0):
        return LeapPython.Listener_on_disconnect(self, arg0)

    def on_exit(self, arg0):
        return LeapPython.Listener_on_exit(self, arg0)

    def on_frame(self, arg0):
        return LeapPython.Listener_on_frame(self, arg0)

    def on_focus_gained(self, arg0):
        return LeapPython.Listener_on_focus_gained(self, arg0)

    def on_focus_lost(self, arg0):
        return LeapPython.Listener_on_focus_lost(self, arg0)

    def on_service_connect(self, arg0):
        return LeapPython.Listener_on_service_connect(self, arg0)

    def on_service_disconnect(self, arg0):
        return LeapPython.Listener_on_service_disconnect(self, arg0)

    def on_device_change(self, arg0):
        return LeapPython.Listener_on_device_change(self, arg0)

    def on_images(self, arg0):
        return LeapPython.Listener_on_images(self, arg0)

    def on_service_change(self, arg0):
        return LeapPython.Listener_on_service_change(self, arg0)

    def on_device_failure(self, arg0):
        return LeapPython.Listener_on_device_failure(self, arg0)

    def on_log_message(self, arg0, severity, timestamp, msg):
        return LeapPython.Listener_on_log_message(self, arg0, severity, timestamp, msg)
    def __disown__(self):
        self.this.disown()
        LeapPython.disown_Listener(self)
        return weakref.proxy(self)

# Register Listener in LeapPython:
LeapPython.Listener_swigregister(Listener)



